using DocumentFormat.OpenXml.Spreadsheet;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ZedCars.Net8.Data;
using ZedCars.Net8.Models;

namespace ZedCars.Net8.Controllers
{
    [ApiController]
    [Route("api/[controller]")]
    public class MigrationController : ControllerBase
    {
        private readonly ZedCarsContext _context;
        private readonly IPasswordHasher<Admin> _passwordHasher;

        public MigrationController(ZedCarsContext context, IPasswordHasher<Admin> passwordHasher)
        {
            _context = context;
            _passwordHasher = passwordHasher;
        }

        [HttpPost("hash-passwords")]
        public async Task<IActionResult> HashPasswords([FromQuery] string secret)
        {
            // Simple security check - replace with your own secret
            if (secret != "migrate-zedcars-2024")
                return Unauthorized(new { message = "Invalid secret" });

            var admins = await _context.Admins.ToListAsync();
            var migratedCount = 0;

            foreach (var admin in admins)
            {
                // PBKDF2 hashed passwords generated by ASP.NET typically start with "AQ"
                if (!admin.Password.StartsWith("AQ"))
                {
                    admin.Password = _passwordHasher.HashPassword(admin, admin.Password);
                    migratedCount++;
                }
            }

            await _context.SaveChangesAsync();

            return Ok(new
            {
                message = $"Migrated {migratedCount} passwords out of {admins.Count} total users",
                migratedCount,
                totalUsers = admins.Count
            });
        }

        [HttpGet("check-passwords")]
        public async Task<IActionResult> CheckPasswords([FromQuery] string secret)
        {
            if (secret != "migrate-zedcars-2024")
                return Unauthorized(new { message = "Invalid secret" });

            var admins = await _context.Admins.ToListAsync();
            var hashedCount = admins.Count(a => a.Password.StartsWith("AQ"));
            var plainTextCount = admins.Count - hashedCount;

            return Ok(new
            {
                totalUsers = admins.Count,
                hashedPasswords = hashedCount,
                plainTextPasswords = plainTextCount
            });
        }
    }
}
